name: generate-iso
on:
  schedule:
    - cron:
        "00 10 * * 1" # build at 10:00 UTC every Monday
  workflow_dispatch:

jobs:
  iso:
    name: Create and Upload ISO
    runs-on: ubuntu-latest
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: iso
        with:
          arch: x86_64
          image_name: bluexp
          image_repo: ghcr.io/winblues
          image_tag: latest
          version: 41
          variant: xfce
          iso_name: bluexp-latest-41.iso

      - name: Upload ISOs and Checksum to R2
        if: github.ref_name == 'main'
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copyto ${{ steps.iso.outputs.iso_path }} R2:ublue-ledif
